=== owenvoke/keep-data/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Keep Schema",
    "description": "A list of castles or fortifications.",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "id": {
                "description": "The unique identifier (UUID v7) of the castle or fortification.",
                "type": "string",
                "format": "uuid"
            },
            "name": {
                "description": "The name of the castle or fortification.",
                "type": "string"
            },
            "country": {
                "description": "The country of the castle or fortification.",
                "$ref": "#/definitions/country"
            },
            "region": {
                "description": "The region of the castle or fortification (this is only relevant for UK castles).",
                "$ref": "#/definitions/region"
            },
            "coordinates": {
                "description": "The coordinates of the castle or fortification.",
                "$ref": "#/definitions/coordinates"
            },
            "accessible": {
                "description": "Whether the castle or fortification is accessible to the public.",
                "type": "boolean"
            },
            "alternativeNames": {
                "$comment": "Use an English version if available, for non-English names include the translation in brackets.",
                "description": "The alternative names of the castle or fortification.",
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "built": {
                "description": "The century or date that the castle or fortification was built.",
                "type": "string",
                "pattern": "^(?:\\d{1,4}|\\d{1,4} BCE|(?:\\d{1,2}|\\d{1,2}-\\d{1,2})(?:st|nd|rd|th) Century|(?:\\d{1,2}|\\d{1,2}-\\d{1,2})(?:st|nd|rd|th) Century BCE)$"
            },
            "condition": {
                "description": "The condition of the castle or fortification.",
                "$ref": "#/definitions/condition"
            },
            "description": {
                "description": "The description of the castle or fortification.",
                "type": "string"
            },
            "homepage": {
                "$comment": "Use an English version if available.",
                "description": "The official homepage of the castle or fortification.",
                "type": "string",
                "format": "uri-reference"
            },
            "ownedBy": {
                "description": "The owner of the castle or fortification.",
                "type": "string"
            },
            "type": {
                "description": "The type of the castle or fortification.",
                "$ref": "#/definitions/type"
            }
        },
        "required": [
            "id",
            "name",
            "country",
            "coordinates",
            "built",
            "condition",
            "ownedBy",
            "type"
        ],
        "additionalProperties": false
    },
    "definitions": {
        "coordinates": {
            "description": "A set of coordinates in the form of latitude and longitude.",
            "type": "object",
            "properties": {
                "latitude": {
                    "description": "The latitude of the coordinates to a maximum of 5 decimal places (within 1.11m accuracy).",
                    "type": "number"
                },
                "longitude": {
                    "description": "The longitude of the coordinates to a maximum of 5 decimal places (within 1.11m accuracy).",
                    "type": "number"
                }
            },
            "required": [
                "latitude",
                "longitude"
            ],
            "examples": [
                {
                    "latitude": 51.48389,
                    "longitude": -0.60440
                }
            ]
        },
        "type": {
            "description": "The type of a castle or fortification.",
            "enum": [
                "Artillery Fort",
                "Concentric",
                "Folly",
                "Fort",
                "Fortified Manor House",
                "Keepless",
                "Motte and Bailey",
                "Palace",
                "Round Keep",
                "Shell Keep",
                "Square Keep",
                "Tower House",
                "Unknown"
            ]
        },
        "condition": {
            "description": "The condition of a castle or fortification.",
            "enum": [
                "Earthworks",
                "Fragmented Remains",
                "Intact",
                "No Visible Remains",
                "Partial Ruins",
                "Partially Restored",
                "Rebuilt",
                "Restored",
                "Ruins"
            ]
        },
        "country": {
            "$comment": "See https://www.iso.org/iso-3166-country-codes.html for more information.",
            "description": "An ISO 3166 identifier for a country.",
            "enum": [
                "AD",
                "AE",
                "AF",
                "AG",
                "AI",
                "AL",
                "AM",
                "AO",
                "AQ",
                "AR",
                "AS",
                "AT",
                "AU",
                "AW",
                "AX",
                "AZ",
                "BA",
                "BB",
                "BD",
                "BE",
                "BF",
                "BG",
                "BH",
                "BI",
                "BJ",
                "BL",
                "BM",
                "BN",
                "BO",
                "BQ",
                "BR",
                "BS",
                "BT",
                "BV",
                "BW",
                "BY",
                "BZ",
                "CA",
                "CC",
                "CD",
                "CF",
                "CG",
                "CH",
                "CI",
                "CK",
                "CL",
                "CM",
                "CN",
                "CO",
                "CR",
                "CU",
                "CV",
                "CW",
                "CX",
                "CY",
                "CZ",
                "DE",
                "DJ",
                "DK",
                "DM",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "EH",
                "ER",
                "ES",
                "ET",
                "FI",
                "FJ",
                "FK",
                "FM",
                "FO",
                "FR",
                "GA",
                "GB",
                "GD",
                "GE",
                "GF",
                "GG",
                "GH",
                "GI",
                "GL",
                "GM",
                "GN",
                "GP",
                "GQ",
                "GR",
                "GS",
                "GT",
                "GU",
                "GW",
                "GY",
                "HK",
                "HM",
                "HN",
                "HR",
                "HT",
                "HU",
                "ID",
                "IE",
                "IL",
                "IM",
                "IN",
                "IO",
                "IQ",
                "IR",
                "IS",
                "IT",
                "JE",
                "JM",
                "JO",
                "JP",
                "KE",
                "KG",
                "KH",
                "KI",
                "KM",
                "KN",
                "KP",
                "KR",
                "KW",
                "KY",
                "KZ",
                "LA",
                "LB",
                "LC",
                "LI",
                "LK",
                "LR",
                "LS",
                "LT",
                "LU",
                "LV",
                "LY",
                "MA",
                "MC",
                "MD",
                "ME",
                "MF",
                "MG",
                "MH",
                "MK",
                "ML",
                "MM",
                "MN",
                "MO",
                "MP",
                "MQ",
                "MR",
                "MS",
                "MT",
                "MU",
                "MV",
                "MW",
                "MX",
                "MY",
                "MZ",
                "NA",
                "NC",
                "NE",
                "NF",
                "NG",
                "NI",
                "NL",
                "NO",
                "NP",
                "NR",
                "NU",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PF",
                "PG",
                "PH",
                "PK",
                "PL",
                "PM",
                "PN",
                "PR",
                "PS",
                "PT",
                "PW",
                "PY",
                "QA",
                "RE",
                "RO",
                "RS",
                "RU",
                "RW",
                "SA",
                "SB",
                "SC",
                "SD",
                "SE",
                "SG",
                "SH",
                "SI",
                "SJ",
                "SK",
                "SL",
                "SM",
                "SN",
                "SO",
                "SR",
                "SS",
                "ST",
                "SV",
                "SX",
                "SY",
                "SZ",
                "TC",
                "TD",
                "TF",
                "TG",
                "TH",
                "TJ",
                "TK",
                "TL",
                "TM",
                "TN",
                "TO",
                "TR",
                "TT",
                "TV",
                "TZ",
                "UA",
                "UG",
                "UM",
                "US",
                "UY",
                "UZ",
                "VA",
                "VC",
                "VE",
                "VG",
                "VI",
                "VN",
                "VU",
                "WF",
                "WS",
                "YE",
                "YT",
                "ZA",
                "ZM",
                "ZW"
            ]
        },
        "region": {
            "$comment": "See https://wikipedia.org/wiki/ISO_3166-2:GB#Other_codes for more information.",
            "description": "A BS 6879 identifier for a region.",
            "enum": [
                "GB-ENG",
                "GB-NIR",
                "GB-SCT",
                "GB-WLS"
            ]
        }
    }
}

=== owenvoke/keep-data/data/gb-nir.json
[
    {
        "id": "019dfe5f-4d97-732b-ba89-8bc1b6b94bce",
        "name": "Audley's Castle",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 54.37958,
            "longitude": -5.57194
        },
        "built": "15-16th Century",
        "condition": "Ruins",
        "homepage": "https://www.communities-ni.gov.uk/heritage-sites/audleys-castle",
        "ownedBy": "Northern Ireland Environment Agency",
        "type": "Tower House"
    },
    {
        "id": "019dfe5f-4d98-7498-a3e1-1d6cfa4ff816",
        "name": "Ballygally Castle",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 54.89929,
            "longitude": -5.86144
        },
        "built": "17th Century",
        "condition": "Intact",
        "ownedBy": "Private",
        "type": "Tower House"
    },
    {
        "id": "019dfe5f-4d98-7498-a3e1-11db43411f05",
        "name": "Belfast Castle",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 54.6428,
            "longitude": -5.9422
        },
        "built": "12-19th Century",
        "condition": "Restored",
        "homepage": "https://www.belfastcity.gov.uk/belfastcastle",
        "ownedBy": "Belfast City Council",
        "type": "Fortified Manor House"
    },
    {
        "id": "019dfe5f-4d98-7498-a3e1-29412f3b4ef6",
        "name": "Benburb Castle",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 54.40998,
            "longitude": -6.7461
        },
        "alternativeNames": [
            "Wingfield Bawn"
        ],
        "built": "17th Century",
        "condition": "Partial Ruins",
        "homepage": "https://benburbpriory.com/what-we-offer/benburb-castle",
        "ownedBy": "Benburb Priory",
        "type": "Keepless"
    },
    {
        "id": "019d6d0a-bb30-721d-b925-542fa89789b9",
        "name": "Carrickfergus Castle",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 54.71367,
            "longitude": -5.80641
        },
        "built": "12th Century",
        "condition": "Intact",
        "homepage": "https://www.communities-ni.gov.uk/heritage-sites/carrickfergus-castle",
        "ownedBy": "Northern Ireland Environment Agency",
        "type": "Square Keep"
    },
    {
        "id": "019d6d0a-bb30-721d-b925-5e77b6930d00",
        "name": "Castle Balfour",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 54.25062,
            "longitude": -7.44525
        },
        "built": "17th Century",
        "condition": "Ruins",
        "homepage": "https://www.communities-ni.gov.uk/heritage-sites/castle-balfour",
        "ownedBy": "Northern Ireland Environment Agency",
        "type": "Square Keep"
    },
    {
        "id": "019dfe5f-4d98-7498-a3e1-142dac33f6ab",
        "name": "Castle Lug",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 54.68881,
            "longitude": -5.86999
        },
        "alternativeNames": [
            "Castle Lugg",
            "Cloughnalarty",
            "Cloughlougherty"
        ],
        "built": "15-16th Century",
        "condition": "Ruins",
        "homepage": "https://www.communities-ni.gov.uk/heritage-sites/castle-lug",
        "ownedBy": "Northern Ireland Environment Agency",
        "type": "Tower House"
    },
    {
        "id": "019d6d0a-bb30-721d-b925-45bf9790794c",
        "name": "Clough Castle",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 54.29214,
            "longitude": -5.83657
        },
        "built": "12-13th Century",
        "condition": "Ruins",
        "homepage": "https://www.communities-ni.gov.uk/heritage-sites/clough-castle",
        "ownedBy": "State Care Historic Monument",
        "type": "Motte and Bailey"
    },
    {
        "id": "019d6d0a-bb30-721d-b925-4a6bf06eda04",
        "name": "Dundrum Castle",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 54.26193,
            "longitude": -5.84496
        },
        "built": "13th Century",
        "condition": "Ruins",
        "homepage": "https://www.communities-ni.gov.uk/heritage-sites/dundrum-castle",
        "ownedBy": "State Care Historic Monument",
        "type": "Round Keep"
    },
    {
        "id": "019d6d0a-bb30-721d-b925-5a465f3a35a8",
        "name": "Dunluce Castle",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 55.21069,
            "longitude": -6.57961
        },
        "built": "13th Century",
        "condition": "Ruins",
        "homepage": "https://www.communities-ni.gov.uk/heritage-sites/dunluce-castle",
        "ownedBy": "Northern Ireland Environment Agency",
        "type": "Square Keep"
    },
    {
        "id": "019d6d0a-bb30-721d-b925-4debd214e03a",
        "name": "Greencastle",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 54.04093,
            "longitude": -6.09702
        },
        "built": "13th Century",
        "condition": "Ruins",
        "homepage": "https://www.communities-ni.gov.uk/heritage-sites/greencastle",
        "ownedBy": "State Care Historic Monument",
        "type": "Square Keep"
    },
    {
        "id": "019d6d0a-bb30-721d-b925-535af73272e3",
        "name": "Harry Avery's Castle",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 54.71335,
            "longitude": -7.39312
        },
        "built": "14th Century",
        "condition": "Ruins",
        "homepage": "https://www.communities-ni.gov.uk/heritage-sites/harry-averys-castle",
        "ownedBy": "Northern Ireland Environment Agency",
        "type": "Motte and Bailey"
    },
    {
        "id": "019d72bd-61f3-7608-962b-f45bc1874971",
        "name": "Killyleagh Castle",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 54.40183,
            "longitude": -5.65321
        },
        "built": "12th Century",
        "condition": "Intact",
        "ownedBy": "Hamilton Family",
        "type": "Square Keep"
    },
    {
        "id": "019dfe5f-4d98-7498-a3e1-243fc86f4308",
        "name": "Kinbane Castle",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 55.22947,
            "longitude": -6.29126
        },
        "built": "17th Century",
        "condition": "Earthworks",
        "homepage": "https://www.communities-ni.gov.uk/heritage-sites/kinbane-castle",
        "ownedBy": "Northern Ireland Environment Agency",
        "type": "Fort"
    },
    {
        "id": "019dfe5f-4d98-7498-a3e1-2ef39acbd1af",
        "name": "Narrow Water Castle",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 54.11118,
            "longitude": -6.27972
        },
        "built": "16th Century",
        "condition": "Intact",
        "homepage": "https://narrowwatercastle.co.uk",
        "ownedBy": "Private",
        "type": "Tower House"
    },
    {
        "id": "019dfe5f-4d98-7498-a3e1-19c53c579c3e",
        "name": "Olderfleet Castle",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 54.84276,
            "longitude": -5.8008
        },
        "built": "13-17th Century",
        "condition": "Ruins",
        "homepage": "https://www.communities-ni.gov.uk/heritage-sites/olderfleet-castle",
        "ownedBy": "Northern Ireland Environment Agency",
        "type": "Tower House"
    },
    {
        "id": "019dfe5f-4d98-7498-a3e1-09a25db42eb3",
        "name": "Quoile Castle",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 54.34985,
            "longitude": -5.69947
        },
        "built": "16-17th Century",
        "condition": "Partial Ruins",
        "homepage": "https://www.communities-ni.gov.uk/heritage-sites/quoile-castle",
        "ownedBy": "Northern Ireland Environment Agency",
        "type": "Tower House"
    },
    {
        "id": "019dfe5f-4d98-7498-a3e1-23b28956b584",
        "name": "Red Bay Castle",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 55.0674,
            "longitude": -6.05528
        },
        "accessible": false,
        "built": "17th Century",
        "condition": "Ruins",
        "ownedBy": "Private",
        "type": "Fort"
    },
    {
        "id": "019dfe5f-4d98-7498-a3e1-0cf2b28f16e9",
        "name": "Sketrick Castle",
        "country": "GB",
        "region": "GB-NIR",
        "coordinates": {
            "latitude": 54.48821,
            "longitude": -5.64812
        },
        "built": "12-16th Century",
        "condition": "Ruins",
        "homepage": "https://www.communities-ni.gov.uk/heritage-sites/sketrick-castle",
        "ownedBy": "Northern Ireland Environment Agency",
        "type": "Tower House"
    }
]
